version: '3'
services:
    server:
        image: server:latest
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        ports:
            - 8080:8080
        environment:
            - PORT=8080
            - NODE_ENV=production
    liedecke-noergaard:
        image: liedecke-noergaard:latest
        build:
            context: ./
            dockerfile: ./apps/liedecke-noergaard/Dockerfile
        ports:
            - 4000:4000
        environment:
            - PORT=4000
            - NODE_ENV=production
    nexus:
        image: nexus:latest
        build:
            context: ./
            dockerfile: ./dashboard/Dockerfile
        ports:
            - 5000:5000
        environment:
            - PORT=5000
            - NODE_ENV=production
    website:
        image: website:latest
        build:
            context: ./
            dockerfile: ./website/Dockerfile
        ports:
            - 3000:3000
        environment:
            - PORT=3000
            - NODE_ENV=production
