version: '3'
services:
    webshop-server:
        image: webshop-server:latest
        build:
            context: ./
            dockerfile: ./projects/webshop/server/Dockerfile
        ports:
            - 8080:8080
        environment:
            - PORT=8080
            - NODE_ENV=production
    webshop-website:
        image: webshop-website:latest
        build:
            context: ./
            dockerfile: ./projects/webshop/client/web/Dockerfile
        ports:
            - 4000:4000
        environment:
            - PORT=4000
            - NODE_ENV=production
    webshop-desktop:
        image: webshop-desktop:latest
        build:
            context: ./
            dockerfile: ./projects/webshop/client/desktop/frontend/Dockerfile
        ports:
            - 5000:5000
        environment:
            - PORT=5000
            - NODE_ENV=production
