packages:
    - "website"
    - "server"
    - "dashboard"
    - "apps/**"
    - "apps/**/server"
    - "apps/**/client"
    - "apps/**/client/**"
    - "libraries/**"
    - "libraries/**/packages/**"
