packages:
    - "projects/**/server"
    - "projects/**/client/**"
    - "projects/**/client/**/frontend"
    - "projects/**/client/**/backend"
    - "packages/**"
    - "packages/angular/**"
    - "packages/react/**"
