packages:
    - "apps/**"
    - "apps/**/server"
    - "apps/**/client/**"
    - "apps/**/client/**/frontend"
    - "apps/**/client/**/backend"
    - "libraries/**"
    - "libraries/resolut/**"
    - "libraries/css-properties/**"
