enum CORPORATE_FORM {
    ENKELTMANDSVIRKSOMHED = 'ENKELTMANDSVIRKSOMHED',
    ANPARTSSELSKAB = 'ANPARTSSELSKAB',
    INTERESSENTSKAB = 'INTERESSENTSKAB',
    AKTIESELSKAB = 'AKTIESELSKAB',
    KOMMANDITSELSKAB = 'KOMMANDITSELSKAB'
}

export default CORPORATE_FORM
