const enum SORTING_OPTION {
    MOST_RECENT = 'MOST_RECENT',
    PRICE_ASSENDING = 'PRICE_ASSENDING',
    PRICE_DECENDING = 'PRICE_DECENDING',
    ALPHABETICALLY = 'ALPHABETICALLY'
}

export default SORTING_OPTION
