export {}
declare global {
  const Article: typeof import('resolut')['Article']
  const Button: typeof import('resolut')['Button']
  const Div: typeof import('resolut')['Div']
  const Field: typeof import('resolut')['Field']
  const Form: typeof import('resolut')['Form']
  const Heading: typeof import('resolut')['Heading']
  const Label: typeof import('resolut')['Label']
  const Link: typeof import('resolut')['Link']
  const Main: typeof import('resolut')['Main']
  const Paragraph: typeof import('resolut')['Paragraph']
  const Section: typeof import('resolut')['Section']
  const Select: typeof import('resolut')['Select']
  const Span: typeof import('resolut')['Span']
  const Text: typeof import('resolut')['Text']
  const atom: typeof import('nanostores')['atom']
  const persistentAtom: typeof import('@nanostores/persistent')['persistentAtom']
  const useStore: typeof import('@nanostores/react')['useStore']
}