export {}
declare global {
  const Article: typeof import('resolut')['Article']
  const Button: typeof import('resolut')['Button']
  const Div: typeof import('resolut')['Div']
  const Field: typeof import('resolut')['Field']
  const Form: typeof import('resolut')['Form']
  const Fragment: typeof import('react')['Fragment']
  const Heading: typeof import('resolut')['Heading']
  const Label: typeof import('resolut')['Label']
  const Link: typeof import('resolut')['Link']
  const Main: typeof import('resolut')['Main']
  const Paragraph: typeof import('resolut')['Paragraph']
  const React: typeof import('react')['default']
  const Section: typeof import('resolut')['Section']
  const Select: typeof import('resolut')['Select']
  const Span: typeof import('resolut')['Span']
  const Suspense: typeof import('react')['Suspense']
  const Text: typeof import('resolut')['Text']
  const atom: typeof import('nanostores')['atom']
  const createContext: typeof import('react')['createContext']
  const createElement: typeof import('react')['createElement']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const memo: typeof import('react')['memo']
  const persistentAtom: typeof import('@nanostores/persistent')['persistentAtom']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useSWR: typeof import('swr')['default']
  const useState: typeof import('react')['useState']
  const useStore: typeof import('@nanostores/react')['useStore']
}