enum Permission {
    PRODUCT = 'PRODUCT',
    PRODUCT_CATEGORY = 'PRODUCT_CATEGORY',
    CUSTOMER = 'CUSTOMER',
    ORDER = 'ORDER',
    INVOICE = 'INVOICE',
    PAYSLIP = 'PAYSLIP',
    PAY_PERIOD = 'PAY_PERIOD',
    FIXED_ASSET_REGISTER = 'FIXED_ASSET_REGISTER',
    FIXED_ASSET_GROUP = 'FIXED_ASSET_GROUP',
    INCOME_STATEMENT = 'INCOME_STATEMENT',
    CREDIT_NOTE = 'CREDIT_NOTE',
    BALANCE_SHEET = 'BALANCE_SHEET',
    ANNUAL_REPORT = 'ANNUAL_REPORT',
    ACCOUNT = 'ACCOUNT',
    API_KEY = 'API_KEY',
    PERMISSION = 'PERMISSION',
    ROLE = 'ROLE',
    CONTENT = 'CONTENT',
    CONTENT_TYPE = 'CONTENT_TYPE',
    CONTENT_TYPE_FIELD = 'CONTENT_TYPE_FIELD',
    LOCALES = 'LOCALES',
    QUOTE = 'QUOTE',
    ANALYTICS = 'ANALYTICS',
    EMPLOYEE = 'EMPLOYEE'
}

export default Permission
