export {}
declare global {
  const Children: typeof import('react')['Children']
  const Fragment: typeof import('react')['Fragment']
  const Input: typeof import('/Users/sigfred/Dropbox/Virketrang/Webudvikling/libraries/resolut/packages/client/src/index')['Input']
  const Modal: typeof import('/Users/sigfred/Dropbox/Virketrang/Webudvikling/libraries/resolut/packages/client/src/index')['Modal']
  const Pagination: typeof import('/Users/sigfred/Dropbox/Virketrang/Webudvikling/libraries/resolut/packages/client/src/index')['Pagination']
  const React: typeof import('react')['default']
  const Suspense: typeof import('react')['Suspense']
  const Table: typeof import('/Users/sigfred/Dropbox/Virketrang/Webudvikling/libraries/resolut/packages/client/src/index')['Table']
  const createContext: typeof import('react-dom')['createContext']
  const createElement: typeof import('react')['createElement']
  const createPortal: typeof import('react-dom')['createPortal']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const memo: typeof import('react')['memo']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
}