name: Webshop Server Deployment

on:
    push:
        branches: [master]

        env:
            PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_ID }}
            REGION: europe-north1
            REPO_NAME: webshop-server

        jobs:
            build-and-deploy:
                name: Setup, Build and Deploy
                runs-on: ubuntu-latest

                steps:
                    - name: Checkout
                        uses: actions/checkout@v3

                    - id: 'auth'
                        uses: 'google-github-actions/auth@v0'
                        with:
                            credentials_json: '${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}'

                    - name: Setup Cloud SDK
                        uses: google-github-actions/setup-gcloud@v0

                    - name: Authorize Docker push
                        run: gcloud auth configure-docker

                    - name: Build and tag the docker image
                        run: |-
                          docker-compose build webshop-server --tag gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

                    - name: Push the image to the Google Artifact Registry
                        run: |-
                            docker push gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA

                    - name: Deploy
                        run: |-
                            gcloud run deploy $REPO_NAME \
                            --region $REGION \
                            --image gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
                            --platform "managed" \
                            --quiet
