name: Nexus Distribution

on:
    push:
        branches: [master]
        tags:
            - 'v*'

        paths:
            - 'apps/nexus/**'
            - 'packages/**'

jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      rust_target: x86_64-unknown-linux-gnu
                    - os: macos-latest
                      rust_target: x86_64-apple-darwin
                    - os: macos-latest
                      rust_target: aarch64-apple-darwin
                    - os: windows-latest
                      rust_target: x86_64-pc-windows-msvc
        runs-on: ${{ matrix.platform }}

        defaults:
            run:
                working-directory: ./apps/nexus

        steps:
            - name: Checkout of repository
              uses: actions/checkout@v3

            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

            - name: Rust setup
              run: curl https://sh.rustup.rs -sSf | sh -s -- -y

            - name: Sync node version and cache
              uses: actions/setup-node@v3
              with:
                  node-version: 'latest'
                  cache: 'npm'

            - name: Install dependencies and build frontend
              run: npm install && npm run build

            - name: Build the application
              uses: tauri-apps/tauri-action@v0

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: ${{ github.ref }}
                  releaseName: 'Nexus v__VERSION__'
                  releaseBody: 'See the assets to download and install this version.'
                  releaseDraft: true
                  prerelease: true
