name: Virketrang Website Deployment

on:
    push:
        branches: [master]

        paths:
            - 'website/**'
            - 'packages/**'
            - '.github/workflows/website-deployment.yaml'

jobs:
    build-and-deploy:
        name: Setup, Build and Deploy the Virketrang Website

        runs-on: ubuntu-latest
        env:
            PROJECT_ID: ${{ secrets.VIRKETRANG_GOOGLE_CLOUD_PROJECT_ID }}
            REGION: europe-north1
            IMAGE_NAME: website

        steps:
            - name: Checkout
              uses: actions/checkout@v3.3.0

            - name: Auth
              uses: 'google-github-actions/auth@v0'
              with:
                  credentials_json: ${{ secrets.VIRKETRANG_GOOGLE_CLOUD_GITHUB_ACTIONS_SERVICE_ACCOUNT }}
                  project_id: ${{ secrets.VIRKETRANG_GOOGLE_CLOUD_PROJECT_ID }}

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v1.1.0

            - name: Authorize Docker push
              run: gcloud auth configure-docker --quiet

            - name: Build and tag the docker image
              run: docker-compose build $IMAGE_NAME

            - name: Push the image to the Google Artifact Registry
              env:
                  GIT_TAG: v0.0.1
              run: |-
                  docker tag $IMAGE_NAME:latest eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
                  docker tag $IMAGE_NAME:latest eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
                  docker push eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
                  docker push eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

            - name: Deploy to Google Cloud Run
              run: |-
                  gcloud run deploy $IMAGE_NAME \
                  --region $REGION \
                  --image eu.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest \
                  --platform "managed" \
                  --quiet
